calculadora:	calculadora.l calculadora.y calculadora.h main.c
	bison -d calculadora.y && \
	flex -ocalculadora.lex.c calculadora.l && \
	cc -o main calculadora.tab.c calculadora.lex.c main.c calculadora.c -lm